### ISSUE TITLE
Allow me to run stages in parallel

### ISSUE THREAD

**Issue by Noviny** [dpisani/cyclist#1]
Hi, thanks for making this, it’s super cool! Love the name.

It would be really good if I could specify some steps that could be run in parallel, instead of everything being single track all the way. Are there any plans to add that feature?

**Comment by dpisani** [comment]
Hi @Noviny,

Thanks for your interest in this project! I'm planning on adding parallel steps in the next release, to facilitate workflows such as watching and re-running builds and tests.

I'm thinking that this can be configured by expanding out the stages within a lifecycle, e.g.
```
"lifecycles": {
  "dev": {
    "stages": [
      "clean",
      {
        "name": "build:watch",
        "parallel": true
      },
      "start"
    ]
  }
}
```

Which would cause the `build:watch` stage to be run in the background when the `dev` lifecycle is run.

Please let me know if this suits your needs or if you had something else in mind.
Thanks!

**Comment by Noviny** [comment]
Biggest question would be around what this means:

Does this mean, `build:watch` starts and then `start` begins immediately? Or that `clean` starts, and `build:watch` begins immediately? Or that if there are other parallel stages next to `build:watch` they will be run in different processes alongside one another?

I think the API I was looking for was:

```json
"lifecycles": {
  "dev": {
    "stages": [
      "clean",
      ["parallel-task-1", "parallel-task-2"]
      "start"
    ]
  }
}
```

Where both parallel tasks are run together, but after `clean`, and before `start`

You're thinking of a different kind of parallelization to me.

**Comment by dpisani** [comment]
My idea was that parallel stages don't wait for the script to finish before moving on to the next stage. So in this example, `clean` would finish, then `build:watch` would begin, then `start` would begin. This way, you could achieve something akin to things like `webpack-dev-server` or Parcel's `watch` command.

Your concept of a parallel group is interesting. Could you give a use case for where you would need something like this?

**Comment by Noviny** [comment]
Use case: In CI I want to run linting, and testing, and type checking. I can let them run in parallel which is faster than waiting for each to finish.

Interesting problem with your thing: You can't start the server until `build:watch` has done a certain amount. You'll need either an arbitrary delay or a way to confirm you're good to continue, even as the process keeps running.

**Comment by dpisani** [comment]
Ok that seems valid. I might still represent that as an object, because every stage should be named. Your case would look like:

```
"lifecycles": {
  "dev": {
    "stages": [
      "clean",
      {
        "name": "validate",
        "tasks": ["lint", "typecheck"]
      },
      "test"
    ]
  }
}
```

As for watching builds, there's a few approaches. One would be to have the next process be robust about artifacts not being ready yet (for example, `http-server` is fine to start without all the assets being present). Another would to do a full build before watching for changes in the next stage, which would make your lifecycle look like

```
clean -> build -> build:watch (in background) -> start
```
I think I'll denote this in config as `"background": true` instead of `"parallel": true` as I intended earlier, since your case is a more 'true' parallel.

**Comment by Noviny** [comment]
> Another would to do a full build before watching for changes in the next stage, which would make your lifecycle look like

This is a bit dangerous, as some watch builds generate slightly different files, or will remove existing assets before starting watching, instead of relying on a cache, so it's not guaranteed to be stable.

**Comment by Noviny** [comment]
```
"lifecycles": {
  "dev": {
    "stages": [
      "clean",
      {
        "name": "validate",
        "parallel": true,
        "tasks": ["lint", "typecheck"]
      },
      "test"
    ]
  }
}
```

Is this your suggestion?

**Comment by dpisani** [comment]
> This is a bit dangerous, as some watch builds generate slightly different files, or will remove existing assets before starting watching, instead of relying on a cache, so it's not guaranteed to be stable.

I agree. I imagine that the tools you use would change what approach you take. I plan on writing a few scaffolds/recipes for some recommended build setups later on, but I'd like to leave the lifecycle runner itself flexible enough to suit a wide range of setups.

Your config snippet looks good to me. Running `cyclist dev` on this example would run `clean` and then `lint` + `typecheck` at the same time, and only run `test` once those are both finished

**Comment by dpisani** [comment]
Added in `@cyclist/runner` version `0.3.0`
